### 作業目標: 了解N-Gram如何藉由文本計算機率

### 為何需要使用馬可夫假設來簡化語言模型的計算?

原本的語言模型利用貝氏定理計算機率時為:
$$
\begin{aligned}
&W = (W_1W_2W_3W_4…W_m) \\
&P(W_1,W_2,W_3,W_4,…,W_m) = P(W_1)*P(W_2|W_1)*P(W_3|W_1,W_2)*…*P(W_m|W_1,…,W_{m-1})
\end{aligned}
$$

為何需要引入馬可夫假設使機率簡化為:
$$
P(W_m|W_1,W_2,W_3,…,W_{m-1}) = P(W_m|W_{m-n+1},W_{m-n+2},…,W_{m-1})
$$

In [1]:
'''
簡化模型，容易理解，就算字串太長也不用算很久
'''

'\n簡化模型，容易理解，就算字串太長也不用算很久\n'

In [2]:
import numpy as np
import pandas as pd
words = ['i', 'want', 'to', 'eat', 'chinese', 'food', 'lunch', 'spend']
word_cnts = np.array([2533, 927, 2417, 746, 158, 1093, 341, 278]).reshape(1, -1)
df_word_cnts = pd.DataFrame(word_cnts, columns=words)
df_word_cnts

      i  want    to  eat  chinese  food  lunch  spend
0  2533   927  2417  746      158  1093    341    278

In [3]:
# 記錄當前字與前一個字詞的存在頻率
bigram_word_cnts = [[5, 827, 0, 9, 0, 0, 0, 2], [2, 0, 608, 1, 6, 6, 5, 1], [2, 0, 4, 686, 2, 0, 6, 211],
                    [0, 0, 2, 0, 16, 2, 42, 0], [1, 0, 0, 0, 0, 82, 1, 0], [15, 0, 15, 0, 1, 4, 0, 0],
                    [2, 0, 0, 0, 0, 1, 0, 0], [1, 0, 1, 0, 0, 0, 0, 0]]

df_bigram_word_cnts = pd.DataFrame(bigram_word_cnts, columns=words, index=words)
df_bigram_word_cnts

          i  want   to  eat  chinese  food  lunch  spend
i         5   827    0    9        0     0      0      2
want      2     0  608    1        6     6      5      1
to        2     0    4  686        2     0      6    211
eat       0     0    2    0       16     2     42      0
chinese   1     0    0    0        0    82      1      0
food     15     0   15    0        1     4      0      0
lunch     2     0    0    0        0     1      0      0
spend     1     0    1    0        0     0      0      0

In [15]:
#請根據給出的總詞頻(df_word_cnts)與bigram模型的詞頻(df_bigram_word_cnts)計算出所有詞的配對機率(ex:p(want|i))
df_bigram_prob = df_bigram_word_cnts.copy()
# df_bigram_prob
df_bigram_prob = df_bigram_prob / df_bigram_prob.sum().sum()
# df_bigram_prob / df_bigram_prob.apply(lambda x: x.sum(),axis=0)

,i,want,to,eat,chinese,food,lunch,spend
i,0.001946,0.321915,0.000000,0.003503,0.000000,0.000000,0.000000,0.000779
want,0.000779,0.000000,0.236668,0.000389,0.002336,0.002336,0.001946,0.000389
to,0.000779,0.000000,0.001557,0.267030,0.000779,0.000000,0.002336,0.082133
eat,0.000000,0.000000,0.000779,0.000000,0.006228,0.000779,0.016349,0.000000
chinese,0.000389,0.000000,0.000000,0.000000,0.000000,0.031919,0.000389,0.000000
food,0.005839,0.000000,0.005839,0.000000,0.000389,0.001557,0.000000,0.000000
lunch,0.000779,0.000000,0.000000,0.000000,0.000000,0.000389,0.000000,0.000000
spend,0.000389,0.000000,0.000389,0.000000,0.000000,0.000000,0.000000,0.000000

由上表可知當前一個字詞(列)是want的時候, 當前字詞(行)是to的頻率在文本中共有608次

In [16]:
#請根據給出的總詞頻(df_word_cnts)與bigram模型的詞頻(df_bigram_word_cnts)計算出所有詞的配對機率(ex:p(want|i))
df_bigram_prob = df_bigram_word_cnts.copy()
df_bigram_prob = df_bigram_prob / df_bigram_prob.sum().sum()
###<your code>###
    
df_bigram_prob

,i,want,to,eat,chinese,food,lunch,spend
i,0.001946,0.321915,0.000000,0.003503,0.000000,0.000000,0.000000,0.000779
want,0.000779,0.000000,0.236668,0.000389,0.002336,0.002336,0.001946,0.000389
to,0.000779,0.000000,0.001557,0.267030,0.000779,0.000000,0.002336,0.082133
eat,0.000000,0.000000,0.000779,0.000000,0.006228,0.000779,0.016349,0.000000
chinese,0.000389,0.000000,0.000000,0.000000,0.000000,0.031919,0.000389,0.000000
food,0.005839,0.000000,0.005839,0.000000,0.000389,0.001557,0.000000,0.000000
lunch,0.000779,0.000000,0.000000,0.000000,0.000000,0.000389,0.000000,0.000000
spend,0.000389,0.000000,0.000389,0.000000,0.000000,0.000000,0.000000,0.000000

### 以Bigram模型下判斷語句是否合理

已知的機率值有
1. p(i|_start_) = 0.25
2. p(english|want) = 0.0011
3. p(food|english) = 0.5
4. p(_end_|food) = 0.68
5. P(want|_start_) = 0.25
6. P(english|i) = 0.0011

請根據已給的機率與所計算出的機率(df_bigram_prob), 試著判斷下列兩個句子哪個較為合理

s1 = “i want english food”

s2 = "want i english food"

In [17]:
'''
use both listed information and the table info to calculate the probability
s1 = 0.25 * 0.321915 * 0.0011 * 0.5
s2 = 0.25 * 0.000779 * 0.0011 * 0.5
because s1>s2, s1 is more likely to happen
'''

'\nuse both listed information and the table info to calculate the probability\ns1 = 0.25 * 0.321915 * 0.0011 * 0.5\ns2 = 0.25 * 0.000779 * 0.0011 * 0.5\nbecause s1>s2, s1 is more likely to happen\n'